version: '3.2'

services: 
  db:
    image: incompanyapi/mysql:1.0
    build: ./db
    container_name: 'incompanyapi_db'
    expose: 
      - "3306"
    environment: 
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my
      MYSQL_USER: my
      MYSQL_PASSWORD: my
    volumes: 
      - ../db/testscr:/testsrc
      - ../db/database:/var/lib/mysql
      - ../db/init:/docker-entrypoint-initdb.d
    networks: 
      - db_backend
  backend: 
    image: incompanyapi/backend:1.0
    build: ./backend
    container_name: 'incompanyapi_backend'
    ports:
      - 8080:8080 
    volumes: 
      - ../backend:/tmp/dev/backend
    working_dir: '/tmp/dev/backend'
    depends_on: 
      - db
    stdin_open: true
    tty: true
    networks: 
      - db_backend
      - local-net
  frontend:
    image: incompanyapi/frontend:1.0
    build: ./frontend
    container_name: incompanyapi_frontend
    volumes: 
      - ../frontend/app:/app
    depends_on: 
      - backend
    stdin_open: true
    tty: true
    networks: 
      - local-net
networks: 
  local-net:
    driver: bridge
  db_backend: 
    driver: bridge
