version: '3.2'

services: 
  db:
    image: incompanyapi/mysql:1.0
    build: ./db
    container_name: 'incompanyapi_db'
    restart: always
    ports: 
      - "3306:3306"
    environment: 
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: my
      MYSQL_DATABASE: my
      MYSQL_USER: my
      MYSQL_PASSWORD: my
      BIND-ADDRESS: 0.0.0.0
    volumes: 
      - ../db/database:/var/lib/mysql
      - ../db/init:/docker-entrypoint-initdb.d
    networks: 
      - local-net
  backend: 
    image: incompanyapi/backend:1.0
    build: ./backend
    container_name: 'incompanyapi_backend'
    volumes: 
      - ../backend:/tmp/dev/backend
    ports: 
      - 8000:8000
    stdin_open: true
    tty: true
    working_dir: '/tmp/dev/backend'
    depends_on: 
      - db
    networks: 
      - local-net
    

  #frontend: 
    #image: incompanyapi/frontend:1.0
    #build: ./frontend
    #container_name: 'incompanyapi_frontend'
    #ports: 
      #- 5000:5000
    #stdin_open: true
    #tty: true
    #volumes: 
     # - ../frontend:/home/user1/dev/frontend
    #depends_on: [backend]

networks:
  local-net:
    driver: bridge